spring.application.name=demo


spring.datasource.url=jdbc:postgresql://localhost:5434/mydb
spring.datasource.username=postgres
spring.datasource.password=12345


server.port=8083
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


telegram.api.id=38254773
telegram.api.hash=1a4027303c7d6cd14fc2cd99450cbb13
telegram.phone=+375292464230

# OpenAI (???????? ???? ?? https://platform.openai.com/api-keys)
openai.api.key=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
openai.model=gpt-3.5-turbo